server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${integration.endpoint.eureka-url}

spring:
  application:
    name: discovery-gateway
  config:
    import:
      - classpath:integration.yaml
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Global Filter tommy
            preLogger: true
            postLogger: true
      routes:
        - id: first-service
          uri: ${integration.endpoint.first-service-url}
          predicates:
            - Path=/first-service/**
          filters:
            - DiscoveryCustomFilter
        #            - AddRequestHeader=first-request, first-request-header2
        #            - AddResponseHeader=first-response, first-response-header2
        - id: second-service
          uri: ${integration.endpoint.second-service-url}
          predicates:
            - Path=/second-service/**
          filters:
            - name: DiscoveryCustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Logging Filter tommy
                preLogger: true
                postLogger: true

          # - AddRequestHeader=second-request, second-request-header2
          # - AddResponseHeader=second-response, second-response-header2
