plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.2'
    id 'io.spring.dependency-management' version '1.1.7'
}

allprojects {
    group = 'com.tommy.study'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(23)
        }
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'

    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }

    ext {
        set('springCloudVersion', "2024.0.0")
    }

    dependencies {
        implementation 'org.springframework.boot:spring-boot-starter-web'
        implementation 'org.springframework.boot:spring-boot-starter'
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

        implementation 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
        annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
        implementation 'com.fasterxml.jackson.core:jackson-databind'

        // aop
        implementation 'org.springframework.boot:spring-boot-starter-aop:3.4.2'

        // vault
        implementation 'org.springframework.cloud:spring-cloud-starter-vault-config'

        // log4j2
        implementation 'org.springframework.boot:spring-boot-starter-log4j2'
        modules {
            module('org.springframework.boot:spring-boot-starter-logging') {
                replacedBy("org.springframework.boot:spring-boot-starter-log4j2", "please use log4j2")
            }
        }

        // swagger
        implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.3'
        
        // h2
        runtimeOnly 'com.h2database:h2'

        // lombok
        compileOnly 'org.projectlombok:lombok'
        annotationProcessor 'org.projectlombok:lombok'
        testAnnotationProcessor 'org.projectlombok:lombok'

        // validation
        implementation 'org.springframework.boot:spring-boot-starter-validation'
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
        }
    }

    tasks.named('compileJava') {
        inputs.files(tasks.named('processResources'))
    }

    tasks.withType(Test).all {
        if (JavaVersion.current() >= JavaVersion.VERSION_13) {
            jvmArgs += [
                    "-XX:+AllowRedefinitionToAddDeleteMethods"
            ]
        }
    }

    test {
        useJUnitPlatform()
    }

    compileJava {
        options.compilerArgs.addAll(['-Xlint:unchecked', '-Xlint:deprecation', '-Amapstruct.defaultComponentModel=spring', '-Amapstruct.defaultInjectionStrategy=constructor', '-Amapstruct.unmappedTargetPolicy=ERROR'])
    }
}


bootJar.enabled = false