spring:
  profiles:
    active: local
    group:
      local: common, local
---
spring:
  config:
    activate:
      on-profile: common
    import:
      - classpath:database.yaml
  application:
    name: study
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
logging:
  log4j2:
    config:
      override: classpath:log4j2/log4j2-base.xml, classpath:log4j2/log4j2-${spring.profiles.active}.xml
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 4298
