spring:
  profiles:
    active: local
    group:
      local: common, local
---
spring:
  config:
    activate:
      on-profile: common
    import:
      - classpath:database.yaml
  application:
    name: study
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 4298
