spring:
  profiles:
    active: local
    group:
      local: local
      test: test

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka
---
spring:
  application:
    name: discovery-first-service
  config:
    activate:
      on-profile: local
server:
  port: 0
---
spring:
  application:
    name: discovery-second-service
  config:
    activate:
      on-profile: test
server:
  port: 0