spring:
  application:
    name: discovery-user-service
server:
  #  port: 9002
  port: 0 # random 포트로 사용하겠다는 뜻
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}} #random port 쓰면 eureka server 에 port=0 로 여러 서비스를 올려도 하나 인스턴스만 떠서 instance_id 를 변경
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka
